import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import PropertyForm from "./components/PropertyFormFirst";


export const metadata: Metadata = {
  title: "Deal Acres",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        
       
        {children}
       
        <Footer/>
        
      
      </body>
    </html>
  );
}
